name: CodeCov

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    name: CodeCov
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Generate Report
        run: |
                pip install coverage
                cd continuousprint && coverage run -m unittest discover -p "*_test.py"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
